describe('Eligibility Form Page Test Cases', () => {

    beforeEach(() => {
        cy.log('inside before')
        cy.visit('https://public:Let$BeC001@bgp-qa.gds-gov.tech')
        cy.get('div#login-button').click()
        cy.login('S1234567A', 'Tan Ah Kow', 'BGPQEDEMO', 'Acceptor')
        cy.newGrantApplication()
        cy.applicationForm()
        
    })

    it('Error in Eligibility Section on Review Page', () => {
        //cy.get('#react-eligibility-sg_registered_check-true').check()
        //cy.get('input[id="react-eligibility-turnover_check-true"]').check()
        cy.get('input[id="react-eligibility-global_hq_check-true"]').check()
        cy.get('input[id="react-eligibility-new_target_market_check-true"]').check()
        cy.get('input[id="react-eligibility-started_project_check-true"]').check()
        cy.get('button[id="next-btn"]').click()
        cy.contactDetailsForm('Name', 'Analyst', '98765432', 'abc@gmail.com')
        cy.proposalForm('Analyst', 'Project Description', 'FTA Consultancy', 'Singapore')
        cy.businessImpactForm('2500.00', '2500.00', '2500.00', '2500.00', '2500.00', '2500.00', '2500.00', '2500.00', 'Rationale for Projection', 'Non Tangible Benefits')
        const filePath = 'ACE_QE_Tech_Challenge_Jun2019.pdf';
        cy.costForm('CST TESTING PTE LTD', filePath, '25')
        cy.declareForm()
        cy.screenshot()
        cy.get('.main h2').should('be.visible').and('have.text','Check Your Eligibility')
        cy.get('.nav.nav-sidebar.sidebar-menu li:nth-of-type(1) div span').should('be.visible').and('have.text', ' 2 ')
    })

    it('Error in Contact Details Section on Review Page', () => {
        cy.eligibilityForm()
        cy.get('input[id="react-contact_info-name"]').type('name')
        cy.get('input[id="react-contact_info-designation"]').type('designation')
        cy.get('input[id="react-contact_info-phone"]').type('98765432')
        //cy.get('input[id="react-contact_info-primary_email"]').type(email)
        cy.get('input[id="react-contact_info-correspondence_address-copied"]').check()
        cy.get('input[id="react-contact_info-copied"]').check()
        cy.get('button[id="next-btn"]').click()
        cy.proposalForm('Analyst', 'Project Description', 'FTA Consultancy', 'Singapore')
        cy.businessImpactForm('2500.00', '2500.00', '2500.00', '2500.00', '2500.00', '2500.00', '2500.00', '2500.00', 'Rationale for Projection', 'Non Tangible Benefits')
        const filePath = 'ACE_QE_Tech_Challenge_Jun2019.pdf';
        cy.costForm('CST TESTING PTE LTD', filePath, '25')
        cy.declareForm()
        cy.screenshot()
        cy.get('.main h2').should('be.visible').and('have.text','Provide Your Contact Details')
        cy.get('.nav.nav-sidebar.sidebar-menu li:nth-of-type(2) div span').should('be.visible').and('have.text', ' 2 ')
    })

    it('Error in Proposal Section on Review Page', () => {
        cy.eligibilityForm()
        cy.contactDetailsForm('Name', 'Analyst', '98765432', 'abc@gmail.com')
       // cy.get('input[id="react-project-title"]').type(projectTitle)
        cy.get('input[id="react-project-start_date"]').click()
        cy.get('td.rdtDay.rdtToday').first().click()
        cy.get('input[id="react-project-end_date"]').click()
        cy.get('td.rdtDay.rdtToday').last().click()
        cy.get('textarea[id="react-project-description"]').type('project Desc')
        cy.get('span[id="react-select-project-activity--value"]').click()
        cy.get('input[role="combobox"]').first().type('FTA Consultancy')
        cy.get('input[role="combobox"]').first().type('{enter}')
        cy.get('span[id="react-select-project-primary_market--value"]').click()
        cy.get('input[role="combobox"]').last().type('Singapore')
        cy.get('input[role="combobox"]').last().type('{enter}')
        cy.get('span[class="bgp-label"]').first().click()
        cy.get('button[id="next-btn"]').click()
        cy.businessImpactForm('2500.00', '2500.00', '2500.00', '2500.00', '2500.00', '2500.00', '2500.00', '2500.00', 'Rationale for Projection', 'Non Tangible Benefits')
        const filePath = 'ACE_QE_Tech_Challenge_Jun2019.pdf';
        cy.costForm('CST TESTING PTE LTD', filePath, '25')
        cy.declareForm()
        cy.screenshot()
        cy.get('.main h2').should('be.visible').and('have.text','Submit Your Proposal')
        cy.get('.nav.nav-sidebar.sidebar-menu li:nth-of-type(3) div span').should('be.visible').and('have.text', ' 1 ')
    })

    it('Error in Business Impact Section on Review Page', () => {
        cy.eligibilityForm()
        cy.contactDetailsForm('Name', 'Analyst', '98765432', 'abc@gmail.com')
        cy.proposalForm('Analyst', 'Project Description', 'FTA Consultancy', 'Singapore')
        cy.get('input[id="react-project_impact-fy_end_date_0"]').click()
        cy.get('td.rdtDay.rdtToday').first().click()
        cy.get('input[id="react-project_impact-overseas_sales_0"]').type('2500')
        cy.get('input[id="react-project_impact-overseas_sales_1"]').type('2500')
        cy.get('input[id="react-project_impact-overseas_sales_2"]').type('2500')
        cy.get('input[id="react-project_impact-overseas_sales_3"]').type('2500')
        cy.get('input[id="react-project_impact-overseas_investments_0"]').type('2500')
        cy.get('input[id="react-project_impact-overseas_investments_1"]').type('2500')
        cy.get('input[id="react-project_impact-overseas_investments_2"]').type('2500')
        cy.get('input[id="react-project_impact-overseas_investments_3"]').type('2500')
        //cy.get('textarea[id="react-project_impact-rationale_remarks"]').type(rational_remark)
        cy.get('textarea[id="react-project_impact-benefits_remarks"]').type('benefits Remarks')
        cy.get('button[id="next-btn"]').click()
        const filePath = 'ACE_QE_Tech_Challenge_Jun2019.pdf';
        cy.costForm('CST TESTING PTE LTD', filePath, '25')
        cy.declareForm()
        cy.screenshot()
        cy.get('.main h2').should('be.visible').and('have.text','Explain The Business Impact')
        cy.get('.nav.nav-sidebar.sidebar-menu li:nth-of-type(4) div span').should('be.visible').and('have.text', ' 1 ')
    })

    it('Error in Cost Section on Review Page', () => {
        cy.eligibilityForm()
        cy.contactDetailsForm('Name', 'Analyst', '98765432', 'abc@gmail.com')
        cy.proposalForm('Analyst', 'Project Description', 'FTA Consultancy', 'Singapore')
        cy.businessImpactForm('2500.00', '2500.00', '2500.00', '2500.00', '2500.00', '2500.00', '2500.00', '2500.00', 'Rationale for Projection', 'Non Tangible Benefits')
        const filePath = 'ACE_QE_Tech_Challenge_Jun2019.pdf';
        cy.wait(2000)
        cy.get('div[id="react-project_cost-vendors-accordion-header"]').click()
        cy.get('button[id="react-project_cost-vendors-add-item"]').click()
        cy.get('input[id="react-project_cost-vendors-0-local_vendor-false"]').click()
        //cy.get('input[id="react-project_cost-vendors-0-vendor_name"]').type(vendor_name)
        cy.get('input[id="react-project_cost-vendors-0-attachments-input"]').attachFile(filePath);
        cy.get('input[id="react-project_cost-vendors-0-amount_in_billing_currency"]').type('25')
        cy.get('button[id="next-btn"]').click()
        cy.declareForm()
        cy.screenshot()
        cy.get('.main h2').should('be.visible').and('have.text','Provide Details of Costs')
        cy.get('.nav.nav-sidebar.sidebar-menu li:nth-of-type(5) div span').should('be.visible').and('have.text', ' 1 ')
    })

    it('Error in Declare Section on Review Page', () => {
        cy.eligibilityForm()
        cy.contactDetailsForm('Name', 'Analyst', '98765432', 'abc@gmail.com')
        cy.proposalForm('Analyst', 'Project Description', 'FTA Consultancy', 'Singapore')
        cy.businessImpactForm('2500.00', '2500.00', '2500.00', '2500.00', '2500.00', '2500.00', '2500.00', '2500.00', 'Rationale for Projection', 'Non Tangible Benefits')
        const filePath = 'ACE_QE_Tech_Challenge_Jun2019.pdf';
        cy.costForm('CST TESTING PTE LTD', filePath, '25')
        cy.wait(2000)
        //cy.get('input[id="react-declaration-criminal_liability_check-false"]').check()
        // cy.get('input[id="react-declaration-civil_proceeding_check-false"]').check()
        // cy.get('input[id="react-declaration-insolvency_proceeding_check-false"]').check()
        // cy.get('input[id="react-declaration-project_incentives_check-false"]').check()
        // cy.get('input[id="react-declaration-other_incentives_check-false"]').check()
        // cy.get('input[id="react-declaration-project_commence_check-false"]').check()
        // cy.get('input[id="react-declaration-related_party_check-false"]').check()
        // cy.get('input[id="react-declaration-covid_safe_check-true"]').check()
        // cy.get('input[id="react-declaration-covid_safe_ques_check-true"]').check()
        cy.get('input[id="react-declaration-consent_acknowledgement_check"]').check()
        cy.get('button[id="review-btn"]').click() 
        cy.screenshot()
        cy.get('.main h2').should('be.visible').and('have.text','Declare & Acknowledge Terms')
        cy.get('.nav.nav-sidebar.sidebar-menu li:nth-of-type(6) div span').should('be.visible').and('have.text', ' 9 ')
    })
})