describe('Eligibility Form Page Test Cases', () => {

    beforeEach(() => {
        cy.log('inside before')
        cy.visit('https://public:Let$BeC001@bgp-qa.gds-gov.tech')
        cy.get('div#login-button').click()
        cy.login('S1234567A', 'Tan Ah Kow', 'BGPQEDEMO', 'Acceptor')
        cy.newGrantApplication()
        cy.applicationForm()
    })

    it('Verify Warning Msg For AllQuestions', () => {
        cy.get('div.main div div:nth-of-type(4) div div div label').should('be.visible')
        cy.get('#react-eligibility-sg_registered_check-false').check()
        cy.get('div.eligibility-advice').should('be.visible').and('have.length', 1)
        cy.screenshot()
        cy.get('div.main span:nth-of-type(1) div span a[href]')
            .should('have.prop', 'href')
            .and('equal', 'https://www.ifaq.gov.sg/BGP/apps/fcd_faqmain.aspx#FAQ_1111145')

        cy.get('div.main div div:nth-of-type(5) div div div label').should('be.visible')
        cy.get('input[id="react-eligibility-turnover_check-false"]').check()
        cy.get('div.eligibility-advice').should('be.visible').and('have.length', 2)
        cy.screenshot()
        cy.get('div.main span:nth-of-type(2) div span a[href]')
            .should('have.prop', 'href')
            .and('equal', 'https://www.ifaq.gov.sg/BGP/apps/fcd_faqmain.aspx#FAQ_1111145')

        cy.get('div.main div div:nth-of-type(6) div div div label').should('be.visible')
        cy.get('input[id="react-eligibility-global_hq_check-false"]').check()
        cy.get('div.eligibility-advice').should('be.visible').and('have.length', 3)
        cy.screenshot()
        cy.get('div.main span:nth-of-type(3) div span a[href]')
            .should('have.prop', 'href')
            .and('equal', 'https://www.ifaq.gov.sg/BGP/apps/fcd_faqmain.aspx#FAQ_1111145')

        cy.get('div.main div div:nth-of-type(7) div div div label').should('be.visible')
        cy.get('input[id="react-eligibility-new_target_market_check-false"]').check()
        cy.get('div.eligibility-advice').should('be.visible').and('have.length', 4)
        cy.screenshot()
        cy.get('div.main span:nth-of-type(4) div span a[href]')
            .should('have.prop', 'href')
            .and('equal', 'https://www.ifaq.gov.sg/BGP/apps/fcd_faqmain.aspx#FAQ_1111145')

        cy.get('div.main div div:nth-of-type(8) div div div label').should('be.visible')
        cy.get('input[id="react-eligibility-started_project_check-false"]').check()
        cy.get('div.eligibility-advice').should('be.visible').and('have.length', 5)
        cy.screenshot()
        cy.get('div.main span:nth-of-type(5) div span a[href]')
            .should('have.prop', 'href')
            .and('equal', 'https://www.ifaq.gov.sg/BGP/apps/fcd_faqmain.aspx#FAQ_1111145')

    })

    it('Verify Saved values on Save&Refresh of EligibilityPage', () => {
        cy.get('#react-eligibility-sg_registered_check-true').check()
        cy.get('input[id="react-eligibility-turnover_check-true"]').check()
        cy.get('input[id="react-eligibility-global_hq_check-true"]').check()
        cy.get('input[id="react-eligibility-new_target_market_check-true"]').check()
        cy.get('input[id="react-eligibility-started_project_check-true"]').check()
        cy.get('#save-btn').click()
        cy.screenshot()
        cy.reload()
        cy.screenshot()
        cy.get('#react-eligibility-sg_registered_check-true').check().should('be.checked')
        cy.get('input[id="react-eligibility-turnover_check-true"]').check().should('be.checked')
        cy.get('input[id="react-eligibility-global_hq_check-true"]').check().should('be.checked')
        cy.get('input[id="react-eligibility-new_target_market_check-true"]').check().should('be.checked')
        cy.get('input[id="react-eligibility-started_project_check-true"]').check().should('be.checked')
        
    })
})
